### ----------------- DEV ------------------ ###

### GET default/index
GET http://localhost:3000
### GET 404
GET http://localhost:3000/404
### GET all contacts
GET http://localhost:3000/contacts
### GET 1 contact
GET http://localhost:3000/contacts/63c0723ecba10a8bdcd6290f
### POST - create contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Tyler", "lastName": "Turner", "email": "tylertucker55@gmail.com", "favoriteColor": "red", "birthday": "09-14-1994"
}
### PUT - update contact
PUT http://localhost:3000/contacts/63ccc2cd8dad9bacdcc77e08 HTTP/1.1
content-type: application/json

{
    "firstName": "Ty", "lastName": "tuck", "email": "tylertucker55@gmail.com", "favoriteColor": "red", "birthday": "09-14-1994"
}
### DELETE contact
DELETE http://localhost:3000/contacts/63ccc37eea4b43de2c495b6a HTTP/1.1

### ----------------- PROD ------------------ ###

### GET default/index
GET https://cse341-psei.onrender.com/
### GET all contacts
GET https://cse341-psei.onrender.com/contacts
### GET 1 contact
GET https://cse341-psei.onrender.com/contacts/63c0723ecba10a8bdcd6290f
### POST - create contact
POST http://cse341-psei.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Tyler", "lastName": "Turner", "email": "tylertucker55@gmail.com", "favoriteColor": "red", "birthday": "09-14-1994"
}
### PUT - update contact
PUT http://cse341-psei.onrender.com/contacts/63ccc2cd8dad9bacdcc77e08 HTTP/1.1
content-type: application/json

{
    "firstName": "Ty", "lastName": "tuck", "email": "tylertucker55@gmail.com", "favoriteColor": "red", "birthday": "09-14-1994"
}
### DELETE contact
DELETE http://cse341-psei.onrender.com/contacts/63ccc37eea4b43de2c495b6a HTTP/1.1