// DEV
###
GET http://localhost:3000
###
GET http://localhost:3000/404
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/63c0723ecba10a8bdcd6290f

// PROD
###
GET https://cse341-psei.onrender.com/
###
GET https://cse341-psei.onrender.com/contacts
###
GET https://cse341-psei.onrender.com/contacts/63c0723ecba10a8bdcd6290f